// <auto-generated />
using System;
using ClubConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubConnect.Migrations
{
    [DbContext(typeof(ClubConnectContext))]
    [Migration("20231209223021_cambioModeloSocio")]
    partial class cambioModeloSocio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubConnect.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaYhoraDelEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LugarDelEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDelEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("eventos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Torneo de Futbol 11",
                            FechaYhoraDelEvento = "09/03/2024 - Horario a definir",
                            LugarDelEvento = "Club Colón de San Justo",
                            NombreDelEvento = "Copa Santa Fe"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Torneo de Tenis",
                            FechaYhoraDelEvento = "16/03/2024 - Horario a definir",
                            LugarDelEvento = "Club Colón de San Justo",
                            NombreDelEvento = "Argentina Open"
                        });
                });

            modelBuilder.Entity("ClubConnect.Models.Instalacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CostoDeReserva")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disponibilidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDeLaInstalacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("instalaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostoDeReserva = 9800,
                            Descripcion = "Cancha de Futbol 7",
                            Disponibilidad = "Si",
                            NombreDeLaInstalacion = "Lionel Messi"
                        },
                        new
                        {
                            Id = 2,
                            CostoDeReserva = 3000,
                            Descripcion = "Cancha de Tenis",
                            Disponibilidad = "Si",
                            NombreDeLaInstalacion = "David Nalbandian"
                        });
                });

            modelBuilder.Entity("ClubConnect.Models.Membresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaDeExpiracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaDeInicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SocioId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDeMembresia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("membresias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Activo",
                            FechaDeExpiracion = "24/12/2023",
                            FechaDeInicio = "24/01/2022",
                            SocioId = 1,
                            TipoDeMembresia = "Asociado"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Activo",
                            FechaDeExpiracion = "23712/2023",
                            FechaDeInicio = "23/08/2015",
                            SocioId = 2,
                            TipoDeMembresia = "Afiliado"
                        });
                });

            modelBuilder.Entity("ClubConnect.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaYHoraDeFin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaYHoraDeInicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstalacionId")
                        .HasColumnType("int");

                    b.Property<int?>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstalacionId");

                    b.HasIndex("SocioId");

                    b.ToTable("reservas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Confirmado",
                            FechaYHoraDeFin = "10/12/2023 - 20:00",
                            FechaYHoraDeInicio = "10/12/2023 - 19:00",
                            InstalacionId = 1,
                            SocioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Confirmado",
                            FechaYHoraDeFin = "10/12/2023 - 23:00",
                            FechaYHoraDeInicio = "10/12/2023 - 21:00",
                            InstalacionId = 2,
                            SocioId = 2
                        });
                });

            modelBuilder.Entity("ClubConnect.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaDeIngresoAlClub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("socios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Sasia",
                            Direccion = "San Martín 2698",
                            Email = "natanaelsasia@gmail.com",
                            FechaDeIngresoAlClub = "24/01/2022",
                            FechaNacimiento = "07/03/2001",
                            Nombre = "Natanael",
                            Telefono = "3498517621"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Porchietto",
                            Direccion = "J. Mantovani 1684",
                            Email = "ezeporchietto@gmail.com",
                            FechaDeIngresoAlClub = "23/08/2015",
                            FechaNacimiento = "14/02/1977",
                            Nombre = "Ezequiel",
                            Telefono = "3498431264"
                        });
                });

            modelBuilder.Entity("ClubConnect.Models.Membresia", b =>
                {
                    b.HasOne("ClubConnect.Models.Socio", "socio")
                        .WithMany()
                        .HasForeignKey("SocioId");

                    b.Navigation("socio");
                });

            modelBuilder.Entity("ClubConnect.Models.Reserva", b =>
                {
                    b.HasOne("ClubConnect.Models.Instalacion", "instalacion")
                        .WithMany()
                        .HasForeignKey("InstalacionId");

                    b.HasOne("ClubConnect.Models.Socio", "socio")
                        .WithMany()
                        .HasForeignKey("SocioId");

                    b.Navigation("instalacion");

                    b.Navigation("socio");
                });
#pragma warning restore 612, 618
        }
    }
}
